server {
    listen       80;
    server_name  localhost;

    # Ocultar la versión de Nginx por seguridad
    server_tokens off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Regla vital para SPA (React Navigation para web)
        # Si un archivo no existe, redirige al index.html
        try_files $uri $uri/ /index.html;
    }

    # Caché para los archivos estáticos (JS, CSS, imágenes) generados
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root   /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # Bloquear acceso a archivos ocultos (por seguridad)
    location ~ /\. {
        deny all;
    }
}
